### ISSUE TITLE
Is this repository used for TextureGAN[CVPR-18] experiments?

### ISSUE THREAD

**Issue by UdonDa** [Cuiyirui/TextureGAN#1]
Is this repository used for TextureGAN[Wenqi Xian+ CVPR-18][https://arxiv.org/abs/1706.02823]experiments?

**Comment by Cuiyirui** [comment]
Yes, this is our implementation version. For the sake of research need, however, we cannot provide training set. Our implementation is based on BicycleGAN, you can train your own dataset by running train.py. The train options is already list in README

**Comment by UdonDa** [comment]
Thank you for your polite explanation!
