### ISSUE TITLE
Dataset available?

### ISSUE THREAD

**Issue by caseyjconger** [Cuiyirui/TextureGAN#2]
Hi,
I was looking to learn about the TextureGAN model and found your repo. Is the contour2shirt dataset available? Thanks!
-Casey

**Comment by Cuiyirui** [comment]
sorry, this dataset is related to our unpublished paper. I will release the dataset recently. If you just learning the code,  you can extract a contour with a clipping cloth and a ground truth. Jointing them horizontally with size 256x512.

**Comment by caseyjconger** [comment]
Gotcha. Thanks for the response.
